### ISSUE TITLE
Reverse Engineering 

### ISSUE THREAD

**Issue by TA2k** [oxygen0211/pyl2h#1]
Hi I also working on a smarthome plugin for the link2home.
I am able to login and receive the device list via cloud with the correct signature. But I'm not able to see the cloud communication to control a device when the app is not in the local Wifi.
I also see only the sending direction of the UDP communication.
Can you please provide information how you trace the UDP communication
Also via email and in German 
tombox2020@gmail.com

**Comment by oxygen0211** [comment]
Hi, thanks for reaching out.

I would rather prefer answering here instead of E-Mail in case someone else might be having the same questions. I have not fully reverse engineered the protocol (yet) but am able to extract the information that is currently important to me. I will write this once as the first answer in English, also for accessibility reasons, but feel free to continue the discussion in German if you will.

For further reference, please have a look at https://github.com/oxygen0211/pyl2h/blob/main/src/udp.py and https://github.com/g3gg0/Sonoff-Tasmota/blob/development/sonoff/l2h.inc which has a more in depth implementation of the protocol already for Tasmota.

For Intercepting the traffic, you can use standard tracers like WireShark. Just make sure to configure it to trace UDP and point it to Port 35932. All Hosts (Devices as well as the Mobile App) will broadcast status updates within your Network on this UDP Port. Control commands such as turning a socket on or off are done via UDP Unicasts on the device's IP on the same port.

The messages are Binary encoded and, as of my current understanding, look roughly like this:
1 Byte Header (0xa1) + 1 Byte Type (0x04 is a request) + 6 Byte Device MAC + 2 Byte message length + 2 Byte sequence number + 1 Byte company code + 1 Byte device type code + 1 Byte authentication code + 1 Byte channel ID + 1 Byte current or desired status (depending if we have a status broadcast or request)

I am currently only changing the MAC, channel ID and desired status in the protocol as I am currently more in a PoC/MVP state with my approach on integrating the devices and don't find as much time for it as I would like to. 

I was also able to capture and replicate some of the essential communication from the App to the cloud (via MITMproxy for intercepting the SSL encryption) which is mainly used for discovering devices - this library is only able to see them after their next status update after starting, i.e. if they are toggled - but that is only existing on my laptop as it is in a far more experimental state and I especially could not extract the signature generation algorithm and is reliant on re-capturing the signature value once it changed. Have you had some more success in that area?

**Comment by TA2k** [comment]
Thanks for the sonoff hint this was very helpful. 
I created a smart home adapter for ioBroker. The adapter is able to login and receive all devices. 
I will loop through all Mac addresses and send a discovery and status request.
And will change the status of the channels. No support for led or lamps
https://github.com/TA2k/ioBroker.link2home
